### PR TITLE
Set highlights for lightspeed.nvim.

### PR DESCRIPTION
**Pull request by delafthi**
See [lightspeed.nvim](https://github.com/ggandor/lightspeed.nvim)
hi

### CODE REVIEW

**Comment by shaunsingh** [comment]
Could you by any chance make the colors match those of hop.nvim https://github.com/shaunsingh/nord.nvim/blob/6571965b8c3780603790f6b658626caa729cba7d/lua/nord/theme.lua#L408?

I just thing that coloring the letter instead of the background looks cleaner

**Comment by delafthi** [comment]
> Could you by any chance make the colors match those of hop.nvim https://github.com/shaunsingh/nord.nvim/blob/6571965b8c3780603790f6b658626caa729cba7d/lua/nord/theme.lua#L408-412?
> 
> I just thing that coloring the letter instead of the background looks cleaner

Of course, I wasn't aware of of hop.nvim.
Additionally, I also need to add the lightspeed.nvim to the supported plugin list.

**Comment by delafthi** [comment]
I tried some different combinations. 
hi
This is what I ended up with. Does it match your expectations? I did not install hop.nvim to compare.

**Comment by shaunsingh** [comment]
Yup, looks perfect. Thank you!

**Pull request merged**
